kumuluzee:
  name: kumuluzee-samples-jpa
  env:
    name: dev
  version: 1.0.0
  cors-filter:
    annotations:
      enabled: true
    servlet:
      allow-origin: "http://localhost:3000"
      allow-subdomains: true
      supported-methods: "GET, POST, PUT, DELETE, OPTIONS, HEAD, TRACE"
      supported-headers: "Content-Type, Authorization"
      exposed-headers: "Content-Type, Authorization"
      max-age: 600
      allow-credentials: true
  server:
    base-url: http://localhost:8081
    http:
      port: 8081
  datasources:
    - jndi-name: jdbc/UsersDB
      connection-url: jdbc:postgresql://localhost:5432/users
      #connection-url: jdbc:postgresql://finance-db:5432/finance
      username: postgres
      password: postgres
      max-pool-size: 20
      connection-timeout: 30000
      pool-name: users-pool

  swagger:
    enabled: true
    ui:
      enabled: true
    spec:
      enabled: true
    base-url: http://localhost:8081
    title: users-service
    version: 1.0.0

  discovery:
    etcd:
      hosts: http://localhost:2379
