apiVersion: apps/v1
kind: Deployment
metadata:
  name: finance-db
  labels:
    app: finance-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: finance-db
  template:
    metadata:
      labels:
        app: finance-db
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          env:
            - name: POSTGRES_DB
              value: finance
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
          ports:
            - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: finance-db
spec:
  selector:
    app: finance-db
  ports:
    - port: 5432
      targetPort: 5432